version: '2'

services:
  # Source
  source:
    image: tianon/true
    user: ${UID}:${GID}
    container_name: ${COMPOSE_PROJECT_NAME}-source
    volumes:
      - ./:${APP_PATH}

  # Database
  db:
    image: postgres:12.1-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: always
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/volumes/sql/:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data

  # Composer
  composer:
    build:
      context: ./.docker/composer
    container_name: ${COMPOSE_PROJECT_NAME}-composer
    user: ${UID}:${GID}
    working_dir: ${APP_PATH}
    environment:
      COMPOSER_ALLOW_SUPERUSER: 0
    volumes_from:
      - source
    # volumes:
    # - $HOME/.composer/cache

  # PHP-FPM
  php:
    build:
      context: ./.docker/php-fpm
      args:
        - INSTALL_OPCACHE=false
        - INSTALL_XDEBUG=true
    container_name: ${COMPOSE_PROJECT_NAME}-php
    environment:
      - UID=${UID}
      - GID=${GID}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CHARSET=${DB_CHARSET}
    user: ${UID}:${GID}
    restart: always
    expose:
      - ${PHP_PORT}
    working_dir: ${APP_PATH}
    depends_on:
      - db
    links:
      - db:${DB_HOST}
    volumes_from:
      - source

  # Yii
  yii:
    user: ${UID}:${GID}
    build:
      context: ./.docker/yii
    container_name: ${COMPOSE_PROJECT_NAME}-yii
    environment:
      - UID=${UID}
      - GID=${GID}
    user: ${UID}:${GID}
    working_dir: ${APP_PATH}
    entrypoint: php yii
    depends_on:
      - db
      - php
    links:
      - db:${DB_HOST}
      - php:${PHP_HOST}
    volumes_from:
      - source

  # Nginx
  nginx:
    build:
      context: ./.docker/nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    working_dir: /etc/nginx
    restart: always
    environment:
      - VIRTUAL_HOST=${APP_HOST},www.${APP_HOST},backend.${APP_HOST},www.backend.${APP_HOST}
      - VIRTUAL_PORT=${APP_PORT}
      - VIRTUAL_NETWORK=proxy
      - HTTPS_METHOD=nohttps
      - NGINX_ROOT=${APP_PATH}
      - NGINX_HOST=${APP_HOST}
      - NGINX_PORT=${APP_PORT_HTTP}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
    volumes_from:
      - source
    volumes:
      - ./.docker/volumes/logs/nginx/:/var/log/nginx
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/site.conf.tmpl:/etc/nginx/site.conf.tmpl
      - /etc/nginx/sites-available
    depends_on:
      - db
      - php
    links:
      - db:${DB_HOST}
      - php:${PHP_HOST}
    expose:
      - ${APP_PORT_HTTP}
      - ${APP_PORT_HTTPS}
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_ROOT $$NGINX_HOST $$PHP_HOST $$PHP_PORT' < /etc/nginx/site.conf.tmpl > /etc/nginx/sites-available/site.conf && nginx -g 'daemon off;'"
    restart: always
    networks:
      - proxy
      - default

volumes:
  db:

networks:
  proxy:
    external:
      name: proxy
