version: '3.7'

services:

  # Database
  db:
    image: postgres:12.1-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: always
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/volumes/sql/:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
  
  # Database Test
  db-test:
    image: postgres:12.1-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-db-test
    restart: always
    expose:
      - ${DB_TEST_PORT}
    environment:
      POSTGRES_DB: ${DB_TEST_DATABASE}
      POSTGRES_USER: ${DB_TEST_USERNAME}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
    volumes:
      - ./.docker/volumes/sql-test/:/docker-entrypoint-initdb.d/
      - db-test:/var/lib/postgresql/data

  # Composer
  composer:
    build:
      context: ./.docker/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}-composer
    working_dir: ${APP_PATH}
    environment:
      - UID=${UID}
      - GID=${GID}
      - COMPOSER_ALLOW_SUPERUSER=0
      - COMPOSER_AUTH=${COMPOSER_AUTH}
    user: ${UID}:${GID}
    entrypoint: composer
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}

  # PHP-FPM
  php:
    build:
      context: ./.docker/php-fpm
      args:
        - INSTALL_OPCACHE=false
        - INSTALL_XDEBUG=true
    container_name: ${COMPOSE_PROJECT_NAME}-php
    environment:
      - UID=${UID}
      - GID=${GID}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CHARSET=${DB_CHARSET}
    user: ${UID}:${GID}
    restart: always
    expose:
      - ${PHP_PORT}
    working_dir: ${APP_PATH}
    depends_on:
      - db
      - db-test
    links:
      - db:${DB_HOST}
      - db-test:${DB_TEST_HOST}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}

  # Postgres web UI
  pgadmin:
    image: dpage/pgadmin4:4.19
    container_name: ${COMPOSE_PROJECT_NAME}-pgadmin
    environment:
      - VIRTUAL_HOST=pgadmin.${APP_HOST}
      - VIRTUAL_PORT=${NGINX_PORT}
      - VIRTUAL_NETWORK=proxy
      - PGADMIN_DEFAULT_EMAIL=${DB_ADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${DB_ADMIN_PASSWORD}
    expose:
      - ${NGINX_PORT}
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    links:
      - db:${DB_HOST}
    restart: always
    networks:
      - proxy
      - default

  # Yii
  yii:
    user: ${UID}:${GID}
    build:
      context: ./.docker/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}-yii
    environment:
      - UID=${UID}
      - GID=${GID}
    user: ${UID}:${GID}
    working_dir: ${APP_PATH}
    entrypoint: php yii
    depends_on:
      - db
      - db-test
      - php
    links:
      - db:${DB_HOST}
      - db-test:${DB_TEST_HOST}
      - php:${PHP_HOST}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}

  # Yii Test
  yii-test:
    user: ${UID}:${GID}
    build:
      context: ./.docker/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}-yii-test
    environment:
      - UID=${UID}
      - GID=${GID}
    user: ${UID}:${GID}
    working_dir: ${APP_PATH}
    entrypoint: php yii_test
    depends_on:
      - db
      - db-test
      - php
    links:
      - db:${DB_HOST}
      - db-test:${DB_TEST_HOST}
      - php:${PHP_HOST}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}

  # Codeception
  codecept:
    user: ${UID}:${GID}
    build:
      context: ./.docker/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}-codecept
    environment:
      - UID=${UID}
      - GID=${GID}
    user: ${UID}:${GID}
    working_dir: ${APP_PATH}
    entrypoint: php vendor/bin/codecept
    depends_on:
      - db
      - db-test
      - php
    links:
      - db:${DB_HOST}
      - db-test:${DB_TEST_HOST}
      - php:${PHP_HOST}
      - nginx:${NGINX_HOST}
      - nginx:backend.${NGINX_HOST}
      - hub:hub.${NGINX_HOST}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}

  # Nginx
  nginx:
    build:
      context: ./.docker/nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    working_dir: /etc/nginx
    restart: always
    environment:
      - VIRTUAL_HOST=${APP_HOST},www.${APP_HOST},backend.${APP_HOST},www.backend.${APP_HOST},api.${APP_HOST}
      - VIRTUAL_PORT=${APP_PORT}
      - VIRTUAL_NETWORK=proxy
      - HTTPS_METHOD=nohttps
      - NGINX_ROOT=${APP_PATH}
      - NGINX_HOST=${APP_HOST}
      - NGINX_PORT=${APP_PORT_HTTP}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}
      - ./.docker/volumes/logs/nginx/:/var/log/nginx
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/site.conf.tmpl:/etc/nginx/site.conf.tmpl
      - /etc/nginx/sites-available
    depends_on:
      - db
      - db-test
      - php
    links:
      - db:${DB_HOST}
      - db-test:${DB_TEST_HOST}
      - php:${PHP_HOST}
    expose:
      - ${APP_PORT_HTTP}
      - ${APP_PORT_HTTPS}
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_ROOT $$NGINX_HOST $$PHP_HOST $$PHP_PORT' < /etc/nginx/site.conf.tmpl > /etc/nginx/sites-available/site.conf && nginx -g 'daemon off;'"
    networks:
      - proxy
      - default

  # Selenium
  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    container_name: ${COMPOSE_PROJECT_NAME}-selenium-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    links:
      - nginx:${NGINX_HOST}
      - nginx:backend.${NGINX_HOST}

  # Chrome
  chrome:
    image: selenium/node-chrome:3.14.0-gallium
    container_name: ${COMPOSE_PROJECT_NAME}-selenium-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    links:
      - nginx:${NGINX_HOST}
      - nginx:backend.${NGINX_HOST}

  # Hub
  hub:
    image: selenium/hub:3.14.0-gallium
    container_name: ${COMPOSE_PROJECT_NAME}-selenium-hub
    environment:
      - VIRTUAL_HOST=hub.${APP_HOST}
      - VIRTUAL_PORT=${HUB_PORT}
      - VIRTUAL_NETWORK=proxy
      - HTTPS_METHOD=nohttps
    expose:
      - ${HUB_PORT}
    links:
      - nginx:${NGINX_HOST}
      - nginx:backend.${NGINX_HOST}
    networks:
      - proxy
      - default

volumes:
  db:
  db-test:
  pgadmin:

networks:
  proxy:
    external:
      name: proxy
